version: '3'

services:
  db:
    container_name: psql
    image: postgres
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "5431:5432"
  backend:
    container_name: backend
    build:
      context: backend/
      dockerfile: Dockerfile
    command: foreman start
    volumes:
      - ./backend:/umbrellio/
    ports:
      - "3001:3000"
    depends_on:
      - db
