# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

# Access to rom-rails generators
require 'rom/sql/rake_task'

require_relative 'config/application'

Rails.application.load_tasks

namespace :db do
  task :seed do
    require Rails.root.join('db', 'seeds.rb')
  end
end
